### ISSUE TITLE
Use scandir.walk on python <3.5?

### ISSUE THREAD

**Issue by Hellowlol** [cdgriffith/Reusables#29]
It seems to be alot faster for windows ^^.

**Comment by cdgriffith** [comment]
Thanks for the suggestions! I will add this as an option for all functions that use `os.walk` currently. That way it functions like `rarfile` does now.

**Comment by cdgriffith** [comment]
Added in f419d78e44a662c781e4de643f36b5b3e5675b3e, will close with 0.8 release. 

If you would like your real name or email @Hellowlol in the Authors file, please let me know what to include 😄

**Comment by Hellowlol** [comment]
Thanks for the quick reply! 😊
