### ISSUE TITLE
Singleton metaclass

### ISSUE THREAD

**Issue by Dogeek** [cdgriffith/Reusables#57]
I sometimes need to implement the Singleton pattern in Python, so I think it'd be handy to have it in this library.

```python
class Singleton(type):
    """Singleton design pattern metaclass. Ensures only one instance of an object exists at any time."""
    _instances = {}
    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]
```

It's a metaclass, since it's easier to use. Below are the tests :

```python
#! /usr/bin/env python
# -*- coding: UTF-8 -*-

import reusables

from .common_test_data import *


class Foo(metaclass=reusables.Singleton):
    def __init__(self, thing):
        self.thing = thing

    def __call__(self):
        return self.thing


class TestSingleton(BaseTestClass):
    """Singleton design pattern test class."""
    def test_singleton(self):
        foo = Foo("BAR")
        self.assertIs(foo, Foo("BAZ"))
        self.assertEqual(foo.thing, "BAR")
        self.assertEqual(Foo("BAZ"), "BAR")

```

**Comment by cdgriffith** [comment]
This is one of those obtuse things that has serval ways to impliment and is version dependant. I am including as you have made great contributions, however it's "hidden" (requires direct import) for now until take reusables full Python 3.x only and get better testing / documentation for. 

```
from reusables.other import Singleton
```

Linking to stackoverflow thread with lots of different implimentation ideas https://stackoverflow.com/questions/6760685/creating-a-singleton-in-python
